config/routes.rb
Rails.application.routes.draw do
  root to: 'word_searches#new'
  resources :word_searches, only: [:new, :create, :show, :index]
end

app/models/null_site.rb
class NullSite
  def method_missing(*args, &block)
    self
  end
end

app/models/site.rb
require 'nokogiri'
require 'open-uri'

class Site
  attr_reader :url
  private :url

  def initialize(url:)
    @url = url
  end

  def site_text
    @site_text ||= sanitized_html.inner_text.downcase.squish
  end

  private

  def sanitized_html
    html.tap { |html| html.xpath('//style|//script').remove }
  end

  def html
  @html ||=
  begin
    Nokogiri::HTML(open url)
  rescue => error
    puts error
    NullSite.new
  end
  end
end

app/models/weighted_word.rb
class WeightedWord < ActiveRecord::Base
  belongs_to :word_search, inverse_of: :weighted_words

  validates :word, presence: true
  validates :word_search, presence: true
  validates :frequency, presence: true

  scope :sorted_by_frequency, -> { order(frequency: :desc) }
  scope :top_ten, -> { sorted_by_frequency.first(10) }

  def self.heaviest
    self.sorted_by_frequency.first
  end
end

app/models/weighted_word_search_maker.rb
class WeightedWordSearchMaker
  attr_reader :words_map, :word_search
  private :words_map, :word_search

  def initialize(word_search:, words_map:)
    @words_map = words_map
    @word_search = word_search
  end

  def make_weighted_words
    ActiveRecord::Base.transaction do
      words_map.map do |word, frequency|
        word_search.weighted_words.build(word: word, frequency: frequency)
      end
      word_search.save
    end
  end
end

app/models/word_search.rb
class WordSearch < ActiveRecord::Base
  has_many :weighted_words, inverse_of: :word_search, dependent: :destroy

  validates :weighted_words, length: { minimum: 1 }
  validates :url, presence: true

  delegate :heaviest,
           :top_ten, to: :weighted_words

  def top_weighted_word
    heaviest.word
  end

  def top_weighted_frequency
    heaviest.frequency
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/word_searches_controller.rb
require 'words'

class WordSearchesController < ApplicationController

  def new
    @word_search = WordSearch.new
  end

  def create
    @word_search = WordSearch.where(word_search_params).first_or_initialize
    if @word_search.persisted?
      render :show
    elsif valid_url? && make_weighted_words(@word_search)
      render :show
    else
      flash.now[:notice] = I18n.t('word_search.errors.unparsable')
      render :new
    end
  end

  def show
  end

  def index
    @word_searches = WordSearch.all
  end

  private

  def word_search_params
    params.require(:word_search).permit(:url)
  end

  def make_weighted_words(word_search)
    WeightedWordSearchMaker.new(word_search: word_search, words_map: words_map)
      .make_weighted_words
  end

  def words_map
    Words.frequency(site_text)
  end

  def site_text
    Site.new(url: word_search_params[:url]).site_text
  end

  def valid_url?
    UrlValidator.valid?(word_search_params[:url])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
header
  h1= link_to t('title'), word_searches_path
  nav= link_to t('nav.new_word_search'), new_word_search_path

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    title= t('title')

    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Londrina+Outline|Josefin+Slab:300,600', type: 'text/css'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = favicon_link_tag

  body
    = render 'layouts/header'
    = yield

app/views/word_searches/index.html.slim
p= t('word_search.past')

table
  tr
    th site
    th word
    th frequency

  - @word_searches.each do |word_search|
    tr
      td= word_search.url
      td= word_search.top_weighted_word
      td= word_search.top_weighted_frequency

app/views/word_searches/new.html.slim
p= t('word_search.new.title')

= simple_form_for @word_search do |f|
  fieldset= f.input :url,
    placeholder: t('word_search.new.url_placeholder'),
    label: false, error: false
  fieldset.errors= f.error :url
  fieldset.errors= flash.now[:notice]
  button= t('word_search.new.submit_button')

app/views/word_searches/show.html.slim
p
  img src="https://media.giphy.com/media/RhPvGbWK78A0/giphy.gif"/

p= t('word_search.show.site_searched', site: @word_search.url)

p
  table
    tr
      th word
      th frequency

    - @word_search.top_ten.each do |weighted_word|
      tr
        td= weighted_word.word
        td= weighted_word.frequency